name: Small TCB builds

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    name: Small TCB builds
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
    - name: Alpine build
      shell: docker build --progress=plain -t acond -f {0} .
      run: |
        FROM rust:alpine
        RUN apk add --no-cache musl-dev openssl-dev openssl-libs-static protobuf-dev git
        COPY . ACON
        RUN cd ACON/acond && \
          CARGO_BUILD_RUSTFLAGS=-Crelocation-model=static cargo build --release --target x86_64-unknown-linux-musl && \
          cargo clean && \
          CARGO_BUILD_RUSTFLAGS=-Ctarget-feature=-crt-static cargo build --release
