name: Small TCB builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare alpine dockerfile
      shell: cp {0} Dockerfile
      run: |
        FROM rust:alpine
        RUN apk add --no-cache musl-dev openssl-dev openssl-libs-static protobuf-dev git
        COPY . ACON
        RUN cd ACON/acond && \
          CARGO_BUILD_RUSTFLAGS=-Crelocation-model=static cargo build --release --target x86_64-unknown-linux-musl && \
          cargo clean && \
          CARGO_BUILD_RUSTFLAGS=-Ctarget-feature=-crt-static cargo build --release
    - name: Alpine build
      run: docker build --progress=plain -t acond .
